CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    user_name        VARCHAR(255),
    password         VARCHAR(255),
    confirm_password VARCHAR(255),
    email            VARCHAR(255),
    phone_number     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);